# NumPy 2

In [3]:
import numpy as np

In [3]:
# NumPy array

my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
# vs. python list

my_list = list(range(1000000))

# Multiplicacion de cada secuencia x2

In [7]:
# Comprobamos que NumPy es mucho mas rapido que python sin librerias

%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 65.3 ms


In [10]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 3.51 s


# El array multidimensional de NumPy o ndarray

In [12]:
# Generador de valores aleatorios en NumPy
# En este caso una matriz o array de 2 filas x 3 columnas

data = np.random.randn(2, 3)
data

array([[-0.00796744,  0.31384473, -1.75401946],
       [ 2.13757661, -0.62864451,  0.17531495]])

In [14]:
# Aplicacion de operaciones sobre los elementos de un array

data * 2

array([[-0.01593487,  0.62768946, -3.50803893],
       [ 4.27515322, -1.25728903,  0.35062991]])

In [18]:
# Puedes utilizar el operador ** o np.power(base, exponente)
# Mas recomendable power

data ** 2

array([[6.34800518e-05, 9.84985138e-02, 3.07658428e+00],
       [4.56923376e+00, 3.95193925e-01, 3.07353330e-02]])

In [19]:
np.power(data, 2)

array([[6.34800518e-05, 9.84985138e-02, 3.07658428e+00],
       [4.56923376e+00, 3.95193925e-01, 3.07353330e-02]])

In [21]:
# numero e^data

np.exp(data)

array([[0.99206422, 1.3686772 , 0.17307687],
       [8.4788651 , 0.53331421, 1.19162146]])

# Operaciones entre array (con dimensiones compatibles)

In [22]:
data2 = range(3)
data2

range(0, 3)

In [23]:
np.power(data, data2)

array([[ 1.        ,  0.31384473,  3.07658428],
       [ 1.        , -0.62864451,  0.03073533]])

In [25]:
data_A = np.random.randn(3, 2)
data_A

array([[-0.17609124,  0.89753618],
       [ 1.63342615,  0.50937111],
       [-0.14932932, -0.32349979]])

In [27]:
data_A * data_A

array([[0.03100812, 0.80557119],
       [2.66808098, 0.25945892],
       [0.02229925, 0.10465211]])

In [28]:
# En NumPy la multiplicacion de arrays no es la misma que la mulriplicacion de matrices

# Operaciones con matrices


In [29]:
# Multiplicacion de matrices ->> matriz1.dot(matriz2)

data_A.dot(data)

array([[ 1.91995533, -0.6194965 ,  0.46621898],
       [ 1.07580554,  0.19242884, -2.77576088],
       [-0.69031581,  0.15650015,  0.20521218]])

In [30]:
data.dot(data_A)

array([[ 0.77597171,  0.7201373 ],
       [-1.42943257,  1.54162463]])

# Operaciones binarias con arrays

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [32]:
a == b

array([False,  True, False,  True])

In [33]:
a > b

array([False, False,  True, False])

In [34]:
c = np.array([1, 2, 3, 4])

In [35]:
np.array_equal(a, b)

False

In [36]:
np.array_equal(a, c)

True

# Operaciones logicas

In [37]:
a = np.array([1, 1, 0, 0], dtype = bool)
b = np.array([1, 0, 1, 0], dtype = bool)

In [40]:
# OR logico

np.logical_or(a, b)

array([ True,  True,  True, False])

In [41]:
# ANS logico

np.logical_and(a, b)

array([ True, False, False, False])

# Trasposicion de arrays

In [42]:
data.T

array([[-0.00796744,  2.13757661],
       [ 0.31384473, -0.62864451],
       [-1.75401946,  0.17531495]])

# Generacion de datos de prueba y organizacion matricial/array

In [43]:
# Generacion de un array con nueve datos de forma 3x3

a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
# Realizamos cambios sobre la matriz original que son permanentes

a.T[0,2] = 999

In [46]:
# La trasposicion de un array egnera una vista del original

a.T

array([[  0,   3, 999],
       [  1,   4,   7],
       [  2,   5,   8]])

In [47]:
a

array([[  0,   1,   2],
       [  3,   4,   5],
       [999,   7,   8]])

# Opciones de triangulacion de un array

In [53]:
# Triangular superior triu numpy.triu
# np.triu(m, k = o)

np.triu([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], k)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [60]:
# Triangular inferior tril

np.tril([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

# Visualizacion de la estructura y tipo de datos de un objeto

In [56]:
# Forma de una matriz (a, b)

data.shape

(2, 3)

In [58]:
data.dtype

dtype('float64')

# Creacion de arrays a partir de objetos tipo lista

In [62]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [64]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [65]:
# Creacion de arrays a partir de listas de listas

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [67]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
arr1.dtype

dtype('float64')

In [69]:
arr2.dtype

dtype('int32')

In [70]:
# Hay otras formas de crear arrays como zeros, ones, empty o arange

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [81]:
# Creacion de un array con ceros o "basura" numerica
# Casi cero pero no son cero
# np.empty(dos matrices, 3 filas, 2 columnas)

np.empty((2, 3, 2))

array([[[1.42763871e-311, 2.86558075e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 5.74084271e+169]],

       [[5.89233539e-091, 4.42510229e-062],
        [3.63382427e+174, 2.35950273e+184],
        [6.48224659e+170, 5.82471487e+257]]])

In [74]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [78]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
# Hasta ahora hemos dejado que NumPy infiera el tipo de dato de nuestro array a partir de los datos de las listas
# Ahora vamos a ver como podemos controlar  el tipo de dato con la opcion, dtype(data type)

arr1 = np.array([1, 2, 3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [84]:
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3])

In [86]:
# 128-bit complex floating-point number

arr2_ABC = np.array([1, 2, 3], dtype = np.complex128)
arr2_ABC

array([1.+0.j, 2.+0.j, 3.+0.j])

In [87]:
# Conversion de tipos de datos con el metodo astype

arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [88]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [89]:
# string_ y unicode_

arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [92]:
string_arr = arr.astype(np.string_)
string_arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [94]:
string_arr.dtype

dtype('S11')

In [95]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [97]:
unicode_arr = arr.astype(np.unicode_)
unicode_arr

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [98]:
unicode_arr.dtype

dtype('<U11')

In [100]:
# Prueba

arr = np.array([3.2, 2.4, 3.4, 76.4])

In [103]:
int_arr = arr.astype(np.int32)
int_arr

array([ 3,  2,  3, 76])

In [105]:
# La parte decimal se pierde y no se puede volver

arr = int_arr.astype(np.float64)
arr

array([ 3.,  2.,  3., 76.])

# Importacion de datos desde ficheros de texto como cadenas string y conversion en datos numericos

In [107]:
numeric_strings = np.array(['1,24', '-5,6', '42'], dtype = np.string_)

In [108]:
# Hay que convertir

# Indexado y troceado/extraccion de datos

In [110]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
# Extraer un dato de un array

arr[5]

5

In [112]:
# Extraer una porcion (slices) de datos de un array

arr[5:8]

array([5, 6, 7])

In [113]:
# Modificar los datos de una posicion del array

arr[5] = 120
arr

array([  0,   1,   2,   3,   4, 120,   6,   7,   8,   9])

In [116]:
# IMPORTANTE
# A diferencia de las listas de python, los slices de arrays son vistas de los mismos, no coias
# por lo tanto cualquier modificacion de la vista resulta una modificacion de la original

arr_slice = arr[5:8]
arr_slice

array([120,   6,   7])

In [123]:
# Litecoin

def crypto():
    return (120/60.5334)*int(input('¿A cuanto esta el Litecoin? '))
crypto()

¿A cuanto esta el Litecoin? 65


128.8544836404365

In [120]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr_AB = np.copy(arr)
arr_AB

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
arr_AB[3] = 240
arr_AB

array([  0,   1,   2, 240,   4,   5,   6,   7,   8,   9])

In [132]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
# Note that np.copy is a shalow copy and will not copy object elements within arrays
# To ensure all elements within an object array are copied, use copy.deepcopy

In [126]:
a = np.array([1, 'm', [2, 3, 4]], dtype = object)
a

array([1, 'm', list([2, 3, 4])], dtype=object)

In [127]:
import copy

c = copy. deepcopy(a)

In [128]:
# Cambiamos de la posicion 2 del array, la posicion 0 de es lista por un 10

c[2][0] = 10
c

array([1, 'm', list([10, 3, 4])], dtype=object)

In [129]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)

In [133]:
# Otros metodos para copiar arrays
# ndarray.copy en el metodo propuesto por NumPy

# Arrays multidimensionales

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[0]

array([1, 2, 3])

In [138]:
# Las dos celdas de a continuacion hacen lo mismo 

arr2d[0][2]

3

In [141]:
arr2d[0,2]

8

In [143]:
arr2d[0,0], arr2d[2,1]

(1, 8)

In [144]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [145]:
# Extrae el valor 4 de arr3d

arr3d[0,1,0]

4

In [146]:
# Extrae el valor 11 de arr3d 

arr3d[1,1,1]

11

In [15]:
# Extrae los valorer [2, 3] y [5, 6] de arr2d

arr2d[:2,1:] # Es como poner [0:2,1:3]

array([[2, 3],
       [5, 6]])

In [17]:
# Extrae los valorer [4, 5] de arr2d

arr2d[1,:2] # Es como poner [1,0:2]

array([4, 5])

In [19]:
# Extrae la primera columna

arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [25]:
# modifica los valores de las columnas 1 y 2, estableciendo su nuevo valor a cero

arr2d[:,1:] = 0
arr2d

array([[0, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

# Metodos matematicos y financieros dentro de NumPy

In [34]:
arr = np.random.randn(5,4)
arr

array([[ 0.76248502,  0.64381381, -0.32382923, -0.04397406],
       [-0.5576121 , -0.68254248,  1.07206796, -0.18225302],
       [-0.34967943,  1.03647161, -0.1484312 ,  1.24168165],
       [-0.51529199, -1.34204038, -0.99576552,  0.98942911],
       [ 0.25333271,  0.97541126, -1.22688743, -0.20738819]])

In [35]:
# Media

np.mean(arr)

0.0199499051689312

In [36]:
# Tambien puede ser como un metodo

arr.mean()

0.0199499051689312

In [37]:
# Media de los elementos de cada FILA

arr.mean(axis = 1)

array([ 0.25962389, -0.08758491,  0.44501066, -0.46591719, -0.05138291])

In [38]:
# Media de los elementos de cada COLUMNA

arr.mean(axis = 0)

array([-0.08135316,  0.12622276, -0.32456908,  0.3594991 ])

In [39]:
# Ejercicio: Calcula la suma de los elementos de cada fila y de cada columna de arr

arr.sum(axis = 1) # Fila

array([ 1.03849554, -0.35033964,  1.78004263, -1.86366878, -0.20553165])

In [40]:
arr.sum(axis = 0)

array([-0.40676579,  0.6311138 , -1.62284541,  1.7974955 ])

In [42]:
# cumsum y cumprod no agregansino que lo que produce un nuevo array

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
# Freciencia acumulada

arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [44]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [45]:
arr = np.array ([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [46]:
# Ejercicio: Calcula la suma acumulada por filas y columnas

arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [47]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

# Ordenaciond e arrays

In [48]:
arr = np.random.randn(6)
arr

array([ 0.53601434, -2.43577209, -0.84243769,  0.40716961,  1.79632491,
       -1.7897553 ])

In [50]:
arr.sort()
arr

array([-2.43577209, -1.7897553 , -0.84243769,  0.40716961,  0.53601434,
        1.79632491])

In [52]:
arr = np.random.randn(5, 3)
arr

array([[ 0.72943466,  0.12897995,  1.46979456],
       [-2.45240437,  0.64765498, -1.26071   ],
       [ 1.92889741, -1.6407189 , -0.2137249 ],
       [ 0.72160061,  0.68040794,  0.60041002],
       [ 0.97620612, -0.15351631, -0.92123106]])

In [56]:
# Ordena por filas

arr.sort(1)
arr

array([[ 0.12897995,  0.72943466,  1.46979456],
       [-2.45240437, -1.26071   ,  0.64765498],
       [-1.6407189 , -0.2137249 ,  1.92889741],
       [ 0.60041002,  0.68040794,  0.72160061],
       [-0.92123106, -0.15351631,  0.97620612]])